name: Build & Release Fonts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y fontforge python3 openjdk-17-jre zip woff2

      - name: Download BitsNPicas
        run: curl -L -o BitsNPicas.jar https://github.com/kreativekorp/bitsnpicas/releases/download/v2.0.2/BitsNPicas.jar

      - name: Generate fonts
        run: |
          mkdir -p build/{ttf,otb,bdf,woff2}
          for f in src/*.sfd; do
            name=$(basename "${f%.sfd}")
            # TTF
            java -jar BitsNPicas.jar convertbitmap -f ttf -o build/ttf/${name}.ttf "$f"
            # OTB & BDF
            fontforge -lang=ff -c "Open('$f'); Generate('build/otb/${name}.otb')"
            fontforge -lang=ff -c "Open('$f'); Generate('build/bdf/${name}.bdf')"
            # WOFF2
            woff2_compress build/ttf/${name}.ttf
            mv build/ttf/${name}.woff2 build/woff2/${name}.woff2
          done

      - name: Zip outputs
        run: |
          cd build
          zip -r ../scientifica-ttf.zip ttf
          zip -r ../scientifica-otb.zip otb
          zip -r ../scientifica-bdf.zip bdf
          zip -r ../scientifica-woff2.zip woff2

      - name: Create release tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v1.0.${{ github.run_number }}
          git push origin v1.0.${{ github.run_number }}

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: |
            scientifica-ttf.zip
            scientifica-otb.zip
            scientifica-bdf.zip
            scientifica-woff2.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
